### ISSUE TITLE
We need thematic images

### ISSUE THREAD

**Issue by pavanvo** [Robotkiller001/Megaglest-Improved-Mod#2]
We need thematic images like that
![mechEmptyGrid](https://user-images.githubusercontent.com/44589046/187070908-990b73c9-4273-466a-96cf-be3c3e6103a8.jpg)
for every faction

**Comment by Robotkiller001** [comment]
I have those blank backgrounds for icons.  But i think is gonna be complicated to give this to every unit for every faction and for the already existing mods.

**Comment by pavanvo** [comment]
@Robotkiller001 I create PR [#30](https://github.com/MegaGlest/megaglest-data/pull/30) which move cancel images to root of factions. 
So, this background blanks, we can like that. One per faction.

I will add to engine possibility to read this, and if some mode is not provide this image, engine will render some default "empty image"

**Comment by Robotkiller001** [comment]
Where can i send you the backgrounds?

**Comment by pavanvo** [comment]
@Robotkiller001, I create same PR for improved mod.
I think if you agree with it, you can upload backgrounds, to the factions folders, and I'll add it to my main repo PR

**Comment by Robotkiller001** [comment]
Done
