### ISSUE TITLE
Technician can mine stone with  "mine gold" command

### ISSUE THREAD

**Issue by pavanvo** [Robotkiller001/Megaglest-Improved-Mod#4]
The technician can mine stone with  "mine gold" command

I think can choose one

- rename command
- remove following line with "stone"

https://github.com/Robotkiller001/Megaglest-Improved-Mod/blob/63e83c1df585437046079dd7d40bdafc5fd36cb0/megapack_improved_dev/factions/tech/units/technician/technician.xml#L378

**Comment by Robotkiller001** [comment]
Fixed
